let g:VM_mouse_mappings = 0
let g:VM_maps = {}
let g:VM_maps['Select Operator'] = 'gs'
let g:VM_maps['Undo'] = 'u'
let g:VM_maps['Redo'] = '<C-R>'
let g:VM_maps['Find Under'] = '<C-E>'
let g:VM_maps['Find Subword Under'] = '<C-E>'
let g:VM_maps['Select h'] = '<M-Left>'
let g:VM_maps['Select l'] = '<M-Right>'
let g:VM_maps['Find Operator'] = ''
let g:VM_Extend_hl = 'IncSearch'
let g:VM_Mono_hl = 'IncSearch'
let g:VM_Insert_hl = 'Special'
let g:VM_silent_exit = 1
let g:VM_show_warnings = 0
