-- stylua: ignore start
local M = {}

M.autopairs    =  require('modules.config.autopairs')
M.blankline    =  require('modules.config.blankline')
M.colo         =  require('modules.config.colo')
M.cmp          =  require('modules.config.cmp')
M.comment      =  require('modules.config.comment')
M.copilot      =  require('modules.config.copilot')
M.dadbod       =  require('modules.config.dadbod')
M.dashboard    =  require('modules.config.dashboard')
M.dap          =  require('modules.config.dap')
M.dapui        =  require('modules.config.dapui')
M.feline       =  require('modules.config.feline')
M.gitsigns     =  require('modules.config.gitsigns')
M.lspkind      =  require('modules.config.lspkind')
M.mason        =  require('modules.lspconfig.mason')
M.noice        =  require('modules.config.noice')
M.notify       =  require('modules.config.notify')
M.null_ls      =  require('modules.lspconfig.null-ls')
M.nvim_tree    =  require('modules.config.nvim-tree')
M.oil          =  require('modules.config.oil')
M.project      =  require('modules.config.project')
M.telescope    =  require('modules.config.telescope')
M.todo         =  require('modules.config.todo')
M.treesitter   =  require('modules.config.treesitter')
M.trouble      =  require('modules.config.trouble')
M.autopairs    =  require('modules.config.autopairs')
M.lsp          =  require('modules.lspconfig')
M.roadrunner   =  require('modules.config.roadrunner')
M.rust_tools   =  require('modules.lspconfig.rust-tools')

return M
